### PR TITLE
Switch to using compatible requirements everywhere

### PR DESCRIPTION
**Pull request by jkodumal**

### CODE REVIEW

**Comment by jkodumal** [comment]
Addresses #35

**Comment by albertyw** [comment]
The current version of requests is 2.9.1 (http://docs.python-requests.org/en/latest/) and `requests~=2.4.0` will only allow versions `2.4.*`.  It would require more testing, but perhaps `requests>=2.4.0` is the way to go?

**Comment by albertyw** [comment]
On second thought, until pytest is testing different package versions along with different python versions, it would also be a good idea to set a max version so that a backwards incompatible release doesn't break the client.  `requests` and `future` are pretty darn stable, but I'm not sure about `sseclient` and `CacheControl`.

**Comment by albertyw** [comment]
looks good to me

**Pull request merged**
